import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {toast} from 'react-toastify';
import {createCourse,deleteCourse,getCourses} from '../api/studentAPI';
const empty={courseCode:'',courseName:'',department:'',credits:3,semester:'Semester 1'};
export default function CourseManagement(){const[courses,setCourses]=useState([]),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
const load=async()=>{try{setLoading(true);const d=await getCourses();setCourses(Array.isArray(d)?d:[])}catch(x){toast.error(x.response?.data?.error||'Unable to load courses')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const submit=async ev=>{ev.preventDefault();try{setSaving(true);await createCourse({...form,credits:Number(form.credits)});toast.success('Course added successfully');setForm(empty);load()}catch(x){toast.error(x.response?.data?.error||'Failed to add course')}finally{setSaving(false)}};
const remove=async id=>{if(!window.confirm('Delete this course?'))return;try{await deleteCourse(id);toast.success('Course deleted');load()}catch(x){toast.error(x.response?.data?.error||'Failed to delete course')}};
return <main className="container enrollment-page"><header className="enrollment-hero"><div><span className="enrollment-eyebrow">ACADEMIC ADMINISTRATION</span><h2>Course Management</h2><p>Maintain the course catalog used by student enrollment.</p></div><div className="enrollment-hero-actions"><Link to="/Enroll" className="enrollment-hero-link">← Analytics</Link><Link to="/course-enrollment" className="enrollment-hero-link primary">Enroll Student</Link></div></header><section className="management-grid"><article className="management-card"><div className="chart-heading"><div><span className="chart-kicker">COURSE CATALOG</span><h4>Add Course</h4></div></div><form className="management-form" onSubmit={submit}><label>Course code<input required className="form-control" value={form.courseCode} onChange={x=>setForm({...form,courseCode:x.target.value.toUpperCase()})} placeholder="e.g. CS301"/></label><label>Course name<input required className="form-control" value={form.courseName} onChange={x=>setForm({...form,courseName:x.target.value})} placeholder="e.g. Operating Systems"/></label><label>Department<input required className="form-control" value={form.department} onChange={x=>setForm({...form,department:x.target.value.toUpperCase()})} placeholder="e.g. CSE"/></label><div className="form-row"><label>Credits<input required min="1" max="10" type="number" className="form-control" value={form.credits} onChange={x=>setForm({...form,credits:x.target.value})}/></label><label>Semester<select className="form-select" value={form.semester} onChange={x=>setForm({...form,semester:x.target.value})}>{Array.from({length:8},(_,i)=><option key={i}>Semester {i+1}</option>)}</select></label></div><button className="btn btn-primary" disabled={saving}>{saving?'Saving...':'+ Add Course'}</button></form></article><article className="management-card course-list-card"><div className="chart-heading"><div><span className="chart-kicker">COURSE CATALOG</span><h4>{courses.length} Courses</h4></div><button className="btn btn-sm btn-outline-secondary" onClick={load}>Refresh</button></div>{loading?<div className="enrollment-empty course-empty">Loading courses...</div>:courses.length?<div className="course-list">{courses.map(c=><div className="course-row" key={c._id}><div><strong>{c.courseCode}</strong><span>{c.courseName}</span><small>{c.department||'All departments'} · {c.semester}</small></div><div className="course-meta"><b>{c.credits}</b><small>credits</small><button className="btn btn-sm btn-outline-danger" onClick={()=>remove(c._id)}>Delete</button></div></div>)}</div>:<div className="enrollment-empty course-empty">No courses yet.</div>}</article></section></main>}