import React,{useEffect,useMemo,useState}from'react';
import {Link,useSearchParams}from'react-router-dom';
import {toast}from'react-toastify';
import {createEnrollment,getAllStudents,getCourses}from'../api/studentAPI';
import './Enroll.css';

export default function CourseEnrollment(){
 const[params]=useSearchParams();
 const[students,setStudents]=useState([]),[courses,setCourses]=useState([]),[form,setForm]=useState({student:params.get('student')||'',course:'',academicYear:new Date().getFullYear(),semester:'Semester 1',status:'Enrolled'}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([getAllStudents(),getCourses()]).then(([s,c])=>{setStudents(Array.isArray(s)?s:[]);setCourses(Array.isArray(c)?c:[])}).catch(x=>toast.error(x.response?.data?.error||'Unable to load enrollment options')).finally(()=>setLoading(false))},[]);
 const selected=useMemo(()=>students.find(s=>s._id===form.student),[students,form.student]);
 const submit=async ev=>{ev.preventDefault();try{setSaving(true);await createEnrollment({...form,academicYear:Number(form.academicYear)});toast.success('Student enrolled successfully');window.location.href='/enrollment-history'}catch(x){toast.error(x.response?.data?.error||'Failed to create enrollment')}finally{setSaving(false)}};
 return <main className="container enrollment-page"><header className="enrollment-hero"><div><span className="enrollment-eyebrow">COURSE REGISTRATION</span><h2>Enroll a Student</h2><p>Create a course enrollment record. It will appear in history and analytics.</p></div><div className="enrollment-hero-actions"><Link to="/Enroll"className="enrollment-hero-link">← Analytics</Link><Link to="/enrollment-history"className="enrollment-hero-link">Enrollment History</Link></div></header><section className="management-card enrollment-form-card">{loading?<div className="enrollment-empty course-empty">Loading students and courses...</div>:!courses.length?<div className="empty-state"><h4>No courses available</h4><p>Create a course before enrolling a student.</p><Link to="/courses"className="btn btn-primary">Manage Courses</Link></div>:<form className="management-form enrollment-form"onSubmit={submit}><label>Student<select required className="form-select"value={form.student}onChange={x=>setForm({...form,student:x.target.value})}><option value="">Select student</option>{students.map(s=><option key={s._id}value={s._id}>{s.studentId} — {s.firstName} {s.lastName}</option>)}</select></label><label>Course<select required className="form-select"value={form.course}onChange={x=>setForm({...form,course:x.target.value})}><option value="">Select course</option>{courses.map(c=><option key={c._id}value={c._id}>{c.courseCode} — {c.courseName} ({c.credits} credits)</option>)}</select></label><label>Academic year<input required type="number"min="2000"max="2100"className="form-control"value={form.academicYear}onChange={x=>setForm({...form,academicYear:x.target.value})}/></label><label>Semester<select className="form-select"value={form.semester}onChange={x=>setForm({...form,semester:x.target.value})}>{Array.from({length:8},(_,i)=><option key={i}>Semester {i+1}</option>)}</select></label><label>Status<select className="form-select"value={form.status}onChange={x=>setForm({...form,status:x.target.value})}><option>Enrolled</option><option>Completed</option><option>Dropped</option></select></label><button className="btn btn-primary enrollment-submit"disabled={saving}>{saving?'Enrolling...':'Enroll Student'}</button></form>}{selected&&<div className="selected-student"><span>Selected student</span><strong>{selected.firstName} {selected.lastName}</strong><Link to={'/students/'+selected._id}>Open student profile →</Link></div>}</section></main>
}
