import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {toast} from 'react-toastify';
import {deleteEnrollment,getEnrollments,updateEnrollment} from '../api/studentAPI';
export default function EnrollmentHistory(){const[records,setRecords]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true);
const load=async()=>{try{setLoading(true);const d=await getEnrollments();setRecords(Array.isArray(d)?d:[])}catch(x){toast.error(x.response?.data?.error||'Unable to load enrollment history')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const filtered=useMemo(()=>records.filter(i=>{const h=[i.student?.studentId,i.student?.firstName,i.student?.lastName,i.course?.courseCode,i.course?.courseName,i.academicYear,i.semester,i.status].join(' ').toLowerCase();return(!query||h.includes(query.toLowerCase()))&&(!status||i.status===status)}),[records,query,status]);
const change=async(id,value)=>{try{await updateEnrollment(id,{status:value,completedAt:value==='Completed'?new Date().toISOString():null});toast.success('Enrollment status updated');load()}catch(x){toast.error(x.response?.data?.error||'Failed to update status')}};
const remove=async id=>{if(!window.confirm('Remove this enrollment record?'))return;try{await deleteEnrollment(id);toast.success('Enrollment removed');load()}catch(x){toast.error(x.response?.data?.error||'Failed to remove enrollment')}};
return <main className="container enrollment-page"><header className="enrollment-hero"><div><span className="enrollment-eyebrow">AUDIT & HISTORY</span><h2>Enrollment History</h2><p>Every course enrollment is linked to its student profile and course record.</p></div><div className="enrollment-hero-actions"><Link to="/Enroll" className="enrollment-hero-link">← Analytics</Link><Link to="/course-enrollment" className="enrollment-hero-link primary">+ Enroll Student</Link></div></header><section className="management-card history-card"><div className="history-toolbar"><input className="form-control history-search" placeholder="Search student, ID, course, semester or year..." value={query} onChange={x=>setQuery(x.target.value)}/><select className="form-select history-status-filter" value={status} onChange={x=>setStatus(x.target.value)}><option value="">All statuses</option><option>Enrolled</option><option>Completed</option><option>Dropped</option></select><button className="btn btn-outline-secondary" onClick={load}>Refresh</button></div><div className="history-result-count">{filtered.length} of {records.length} enrollment records</div>{loading?<div className="enrollment-empty history-empty">Loading history...</div>:filtered.length?<div className="table-responsive enrollment-history-table"><table className="table align-middle"><thead><tr><th>Student</th><th>Course</th><th>Credits</th><th>Semester</th><th>Year</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(i=><tr key={i._id}><td><Link className="history-student-link" to={'/students/'+i.student?._id}>{i.student?.studentId||'—'}<small>{i.student?.firstName} {i.student?.lastName}</small></Link></td><td><strong>{i.course?.courseCode||'—'}</strong><small>{i.course?.courseName||'Course unavailable'}</small></td><td>{i.course?.credits??'—'}</td><td>{i.semester||'—'}</td><td>{i.academicYear||'—'}</td><td><select className={'status-select status-'+String(i.status).toLowerCase()} value={i.status} onChange={x=>change(i._id,x.target.value)}><option>Enrolled</option><option>Completed</option><option>Dropped</option></select></td><td><button className="btn btn-sm btn-outline-danger" onClick={()=>remove(i._id)}>Remove</button></td></tr>)}</tbody></table></div>:<div className="enrollment-empty history-empty">No enrollment records match the current filters.</div>}</section></main>}